export const aiPlanGenerator = {
  // 페이지 제목 및 헤더
  title: "AI Plan Generator",
  subtitle: "Generate personalized plans with AI assistance",
  description:
    "Create comprehensive plans for your projects, chapters, and goals using advanced AI technology.",

  // 메인 섹션
  mainSection: {
    title: "Generate Your Plan",
    description:
      "Tell us about your goals and let AI create a personalized plan for you.",
    generateButton: "Generate Plan",
    generating: "Generating...",
    regenerateButton: "Regenerate",
  },

  // 입력 폼
  form: {
    title: "Plan Details",
    goalLabel: "What's your main goal?",
    goalPlaceholder:
      "e.g., Learn React development, Start a fitness routine, Launch a business",
    timeframeLabel: "Timeframe",
    timeframeOptions: {
      week: "1 Week",
      month: "1 Month",
      quarter: "3 Months",
      halfYear: "6 Months",
      year: "1 Year",
    },
    categoryLabel: "Category",
    categoryOptions: {
      learning: "Learning & Education",
      health: "Health & Fitness",
      career: "Career & Business",
      personal: "Personal Development",
      creative: "Creative Projects",
      other: "Other",
    },
    detailsLabel: "Additional Details (Optional)",
    detailsPlaceholder:
      "Provide more context about your goal, current situation, or specific requirements...",
    submitButton: "Generate Plan",
    submitting: "Generating...",
  },

  // 결과 섹션
  result: {
    title: "Your Generated Plan",
    saveButton: "Save to Chapter",
    exportButton: "Export Plan",
    shareButton: "Share Plan",
    editButton: "Edit Plan",
    regenerateButton: "Regenerate Plan",
    noResult: "No plan generated yet. Fill out the form above to get started.",
    summary: {
      title: "Generated Plan Summary",
      areas: " areas",
      projects: " projects",
      description:
        "Review and save the areas, projects, and tasks generated by AI.",
    },
  },

  // 플랜 구조
  plan: {
    overview: "Plan Overview",
    objectives: "Objectives",
    milestones: "Key Milestones",
    tasks: "Tasks & Actions",
    timeline: "Timeline",
    resources: "Resources & Tools",
    tips: "Tips & Recommendations",
  },

  // 상태 메시지
  status: {
    ready: "Ready to generate your plan",
    generating:
      "AI is analyzing your goals and creating a personalized plan...",
    success: "Plan generated successfully!",
    error: "Failed to generate plan. Please try again.",
    saving: "Saving...",
    saved: "Plan saved successfully!",
  },

  // 모달 및 다이얼로그
  modal: {
    saveTitle: "Save Plan to Chapter",
    saveDescription: "Choose which chapter to save this plan to:",
    saveButton: "Save Plan",
    cancelButton: "Cancel",
    noChapters: "No chapters available. Create a chapter first.",
    createChapterButton: "Create New Chapter",
  },

  // 에러 메시지
  errors: {
    goalRequired: "Please enter your main goal",
    timeframeRequired: "Please select a timeframe",
    categoryRequired: "Please select a category",
    generationFailed:
      "Failed to generate plan. Please check your input and try again.",
    saveFailed: "Failed to save plan. Please try again.",
    networkError: "Network error. Please check your connection and try again.",
  },

  // 도움말 및 팁
  help: {
    goalTip:
      "Be specific about what you want to achieve. The more detailed your goal, the better the plan will be.",
    timeframeTip:
      "Choose a realistic timeframe that matches your goal's complexity.",
    categoryTip:
      "Selecting the right category helps AI provide more relevant suggestions.",
    detailsTip:
      "Include any constraints, preferences, or specific requirements that might affect your plan.",
  },

  // 성공 메시지
  success: {
    planGenerated: "Your personalized plan has been generated!",
    planSaved: "Plan has been saved to your chapter successfully!",
    planExported: "Plan has been exported successfully!",
  },

  // 기존 영역 정보
  existingAreas: {
    title: "Existing Areas Information",
    description:
      "AI will reuse existing areas if similar ones are found, and only create new areas.",
  },

  // 제약 조건 설정
  constraints: {
    timeSettings: {
      title: "Time Settings",
      projectDuration: "Project Duration",
      daysPerWeek: "Days per Week",
      dailyTime: "Daily Available Time",
    },
    preferences: {
      title: "Preference Settings",
      currentLevel: "Current Level",
      intensity: "Progress Intensity",
      activityStyle: "Activity Style",
    },
  },

  // 영역 매칭
  areaMatching: {
    title: "🔄 Area Selection",
    description:
      "Choose whether to match AI-suggested areas with existing ones or create new ones.",
    selectExisting: "Select from existing areas:",
    createNew: "Create as new areas:",
    selected: "✓ Selected",
  },

  // 프로젝트 타입
  projectTypes: {
    repetitive: "Repetitive",
    task: "Task-based",
  },

  // 프로젝트 세부사항
  projectDetails: {
    target: "Target",
    targetCount: "Target Count",
    times: "times",
    items: "items",
    dailyTime: "Daily",
    hours: "hours",
    mainTasks: "Main Tasks:",
    showMore: "Show More",
    showLess: "Show Less",
    moreTasks: "and {count} more tasks",
  },

  // 편집 모드
  edit: {
    projectTitle: "Project Title",
    projectDescription: "Project Description",
    target: "Target",
    dailyTime: "Daily Time (minutes)",
  },
} as const;
